# .github/workflows/build.yml

name: Build and Release Binary

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Build binary with PyInstaller
        run: |
          poetry run pyinstaller orion.spec

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/orion/orion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
