# .github/workflows/build.yml

name: Build and Upload Binary

on:
  push:
    branches:
      - "main"  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Build binary with PyInstaller
        run: |
          poetry run pyinstaller orion.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: orion
          path: dist/orion/



