# .github/workflows/build-and-release.yml

name: Build and Release Binary

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            extension: ""
          - os: macos-latest
            platform: mac
            extension: ""
          - os: macos-latest
            platform: mac
            extension: ""
            arch: arm64
          - os: windows-latest
            platform: windows
            extension: ".exe"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Build binary with PyInstaller
        run: |
          arch=${{ matrix.arch || 'x86_64' }}
          poetry run pyinstaller --clean --onefile --distpath dist/orion --name orion${{ matrix.extension }} --target-arch $arch orion.spec

      - name: Rename binary
        if: matrix.os == 'macos-latest'
        run: |
          mv dist/orion/orion${{ matrix.extension }} dist/orion/orion_${{ matrix.arch }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/orion/orion*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

